ALTER TABLE products
    DROP CONSTRAINT fk_products_on_category;

ALTER TABLE categories RENAME TO products_categories;

CREATE TABLE raw_materials_categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_raw_materials_categories PRIMARY KEY (id)
);

ALTER TABLE raw_materials
    ADD category_id BIGINT;

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES products_categories (id);

ALTER TABLE raw_materials
    ADD CONSTRAINT FK_RAW_MATERIALS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES raw_materials_categories (id);
