CREATE SEQUENCE IF NOT EXISTS food_inputs_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS order_items_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS orders_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS product_food_inputs_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS products_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE food_inputs
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cost             DOUBLE PRECISION,
    cost_per_unit    DOUBLE PRECISION,
    measurement_unit INTEGER,
    name             VARCHAR(255),
    quantity         INTEGER,
    CONSTRAINT food_inputs_pkey PRIMARY KEY (id)
);

CREATE TABLE order_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    quantity   INTEGER,
    total      DOUBLE PRECISION,
    order_id   BIGINT,
    product_id BIGINT,
    CONSTRAINT order_items_pkey PRIMARY KEY (id)
);

CREATE TABLE categories
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code          VARCHAR(255),
    customer_info VARCHAR(255),
    date          TIMESTAMP WITHOUT TIME ZONE,
    total         DOUBLE PRECISION,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE product_food_inputs
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    measurement_unit INTEGER,
    quantity         INTEGER,
    total_cost       DOUBLE PRECISION,
    food_input_id    BIGINT,
    product_id       BIGINT,
    CONSTRAINT product_food_inputs_pkey PRIMARY KEY (id)
);

CREATE TABLE products
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255),
    price            FLOAT,
    profit           DOUBLE PRECISION                        NOT NULL,
    profit_margin    DOUBLE PRECISION                        NOT NULL,
    suggested_price  DOUBLE PRECISION                        NOT NULL,
    total_cost       DOUBLE PRECISION                        NOT NULL,
    integration_name VARCHAR(255),
    sales_quantity   INTEGER,
    total_billed     DOUBLE PRECISION,
    CONSTRAINT products_pkey PRIMARY KEY (id)
);

ALTER TABLE product_food_inputs
    ADD CONSTRAINT fk290rvxk9sj2e1lt7bgxa0vjlg FOREIGN KEY (food_input_id) REFERENCES food_inputs (id) ON DELETE NO ACTION;

ALTER TABLE product_food_inputs
    ADD CONSTRAINT fk395q751tf23j2xfruvlrudpfo FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE NO ACTION;

ALTER TABLE order_items
    ADD CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES categories (id) ON DELETE NO ACTION;

ALTER TABLE order_items
    ADD CONSTRAINT fkocimc7dtr037rh4ls4l95nlfi FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE NO ACTION;