ALTER TABLE raw_materials
    DROP CONSTRAINT fk_food_inputs_on_preparation;

CREATE TABLE preparation_ingredients
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    raw_material_id BIGINT,
    preparation_id  BIGINT,
    quantity        DOUBLE PRECISION,
    total_cost      DOUBLE PRECISION,
    CONSTRAINT pk_preparation_ingredients PRIMARY KEY (id)
);

ALTER TABLE preparation_ingredients
    ADD CONSTRAINT FK_PREPARATION_INGREDIENTS_ON_PREPARATION FOREIGN KEY (preparation_id) REFERENCES preparations (id);

ALTER TABLE preparation_ingredients
    ADD CONSTRAINT FK_PREPARATION_INGREDIENTS_ON_RAW_MATERIAL FOREIGN KEY (raw_material_id) REFERENCES raw_materials (id);

ALTER TABLE raw_materials
    DROP COLUMN preparation_id;